routes/router.py
from flask import Blueprint, abort , request, render_template, redirect, url_for, jsonify
from flask import flash
from flask import Flask
from controls.personaDaoControl import PersonaDaoControl
from models.personaEmisora import PersonaEmisora
from controls.facturaDaoControl import FacturaDaoControl
from models.factura import Factura
from controls.historialDao import HistorialDao
from models.historialRetenciones import HistorialRetenciones
from controls.personaControl import PersonaControl
from controls.facturaControl import FacturaControl
from models.enumTipoRuc import EnumTipoRuc
from flask_cors import CORS
from controls.tda.linked.merge import MergeSort
from controls.tda.linked.quick import QuickSort
from controls.tda.linked.shell import ShellSort
from controls.tda.linked.binarySearch import BinarySearch
from controls.tda.linked.linearSearch import LinearSearch
import json
import json
import json
import time


app = Flask(__name__)
app.secret_key = '1234'

cors = CORS(app)

router = Blueprint('router', __name__)

import secrets

app.secret_key = secrets.token_hex(16)  # Genera una cadena hexadecimal de 16 bytes



#CORS(api)
cors = CORS(router, resource={
    r"/*":{
        "origins":"*"
    }
})

@router.route('/') #SON GETS
def home():
    return render_template('templatepersonas.html')

@router.route('/') #SON GETS
def home1():
    return render_template('templatefacturas.html')

@router.route('/') #SON GETS
def home2():
    return render_template('templateretenciones.html')


@router.route('/personas')
def lista_personas():
    pc = PersonaDaoControl()
    return render_template('personas/listapersonas.html', lista = pc.to_dict())


@router.route('/facturas')
def lista_facturas():
    fc = FacturaDaoControl()
    return render_template('facturas/listafacturas.html', lista = fc.to_dict())

@router.route('/retenciones')
def lista_retenciones():
    hd = HistorialDao()
    return render_template('retenciones/listaretenciones.html', lista = hd.to_dict())



@router.route('/personas/ver')
def ver_personas():
   return render_template('personas/guardarpersonas.html')

@router.route('/facturas/ver')
def ver_facturas():
    dni = request.args.get('dni')
    ruc = request.args.get('ruc')
    return render_template('facturas/guardarfacturas.html', dni=dni, ruc=ruc)

@router.route('/retenciones/ver')
def ver_retenciones():
   return render_template('retenciones/guardarretenciones.html')




@router.route('/personas/guardar', methods=["POST"])
def guardar_personas():
    pd = PersonaDaoControl()
    data = request.form

    if not all(key in data for key in ["apellidos", "nombres", "direccion", "dni", "telefono", "tipoRuc"]):
        abort(400, "Faltan datos necesarios")

    nueva_persona = PersonaEmisora()
    nueva_persona._apellidos = str(data["apellidos"])
    nueva_persona._nombres = str(data["nombres"])
    nueva_persona._direccion = str(data["direccion"])
    nueva_persona._dni = str(data["dni"])
    nueva_persona._telefono = str(data["telefono"])
    
    # Validar y asignar el tipo de RUC
    tipo_ruc = str(data["tipoRuc"])
    if tipo_ruc not in ["8", "10"]:
        abort(400, "Valor de RUC no válido")
    
    tipo_ruc_enum = EnumTipoRuc(int(tipo_ruc))
    nueva_persona._tipoRuc = tipo_ruc_enum.name  # Guardar el nombre del Enum en lugar del valor numérico

    # Obtener la lista de personas para determinar el nuevo ID
    lista_personas = pd._list()
    nuevo_id = lista_personas._lenght + 1  # ID único basado en la longitud de la lista más 1
    nueva_persona._id = nuevo_id

    pd._save(nueva_persona)

    return redirect("/personas", code=302)


@router.route('/facturas/guardar', methods=["POST"])
def guardar_facturas():
    fd = FacturaDaoControl()
    data = request.form
    
    # Imprimir los datos recibidos para depuración
    print("Datos recibidos:", data)
    
    # Validar si los datos mínimos están presentes
    if not all(key in data for key in ["numero", "nombreReceptor", "fechaEmision", "montoTotal", "dni", "ruc"]):
        abort(400, "Faltan datos necesarios")

    nueva_factura = Factura()
    nueva_factura._numero = str(data["numero"]) 
    nueva_factura._nombreReceptor = str(data["nombreReceptor"])
    nueva_factura._fechaEmision = str(data["fechaEmision"])
    nueva_factura._montoTotal = str(data["montoTotal"])
    nueva_factura._dniPersonaEmisora = str(data["dni"])  # Usar el DNI heredado de la persona
    nueva_factura._ruc = str(data["ruc"])  # Usar el RUC heredado de la persona

    lista_facturas = fd._list()
    nuevo_id = lista_facturas._lenght + 1  # ID único basado en la longitud de la lista más 1
    nueva_factura._id = nuevo_id
    
    fd._save(nueva_factura)

    return redirect("/facturas", code=302)


@router.route('/retenciones/guardar', methods=["POST"])
def guardar_retenciones():
    hd = HistorialDao()
    data = request.form

    if not all(key in data for key in ["fecha", "numeroFactura", "porcentaje", "montoRetenido"]):
        abort(400, "Faltan datos necesarios")

    nuevo_historial = HistorialRetenciones()
    nuevo_historial._fecha = str(data["fecha"])
    nuevo_historial._numeroFactura = str(data["numeroFactura"])
    nuevo_historial._porcentaje = str(data["porcentaje"])
    nuevo_historial._montoRetenido = str(data["montoRetenido"])
    
    # Obtener la lista de personas para determinar el nuevo ID
    lista_retenciones = hd._list()
    nuevo_id = lista_retenciones._lenght + 1  # ID único basado en la longitud de la lista más 1
    nuevo_historial._idRetencion = nuevo_id
    
    hd._save(nuevo_historial)

    return redirect("/retenciones", code=302)


@router.route('/personas/editar/<pos>')
def ver_editarPersonas(pos):
    pd = PersonaDaoControl()
    nene = pd._list().get(int(pos)-1)
    print(nene)
    return render_template("personas/modificarpersonas.html", data = nene )

#MODIFICAR PERSONAS
@router.route('/personas/modificar', methods=["POST"])
def modificar_personas():
    pd = PersonaDaoControl()
    data = request.form
    pos = data["id"]
    nene = pd._list().get(int(data["id"]) -1)
    if not "apellidos" in data.keys():
        abort(400)
    
    #TODO ...Validar
    pd._persona = nene
    pd._persona._id = data ["id"]
    pd._persona._apellidos = data["apellidos"]
    pd._persona._nombres = data["nombres"]
    pd._persona._direccion = data["direccion"]
    pd._persona._dni = data["dni"]
    pd._persona._telefono = data["telefono"]
    pd.merge(int(pos)-1)
    return redirect("/personas", code=302)



@router.route('/personas/ordenar', methods=["GET"])
def ordenar_personas():
    sort_method = request.args.get("sortMethod")
    sort_attribute = request.args.get("sortAttribute")
    sort_order = request.args.get("sortOrder")
    descending = sort_order == "descendente"

    pd = PersonaDaoControl()
    lista = pd._list()
    merge_sort = MergeSort()
    quick_sort = QuickSort()
    shell_sort = ShellSort()

    # Convertimos la lista enlazada a un array
    array_personas = lista.toArray

    if sort_method == "merge":
        if descending:
            array_personas = merge_sort.sort_models_descendent(array_personas, sort_attribute)
        else:
            array_personas = merge_sort.sort_models_ascendent(array_personas, sort_attribute)
    elif sort_method == "quick":
        if descending:
            array_personas = quick_sort.sort_models_descendent(array_personas, sort_attribute)
        else:
            array_personas = quick_sort.sort_models_ascendent(array_personas, sort_attribute)
    elif sort_method == "shell":
        if descending:
            array_personas = shell_sort.sort_models_descendent(array_personas, sort_attribute)
        else:
            array_personas = shell_sort.sort_models_ascendent(array_personas, sort_attribute)
    else:
        return "Método de ordenación no válido"

    lista.toList(array_personas)
    return render_template('personas/listapersonas.html', lista=lista.toArray)

@router.route('/personas/buscar', methods=["GET"])
def buscar_personas():
    query = request.args.get("query")
    search_attribute = request.args.get("searchAttribute")
    search_method = request.args.get("metodo_busqueda")
    starts_with = request.args.get("startsWith") == "true"

    pd = PersonaDaoControl()
    lista = pd._list()
    array_personas = lista.toArray._array


    lista1 = []
    result = []

    if search_method == "binario":
        result = BinarySearch.search(array_personas, search_attribute, query, starts_with)
    elif search_method == "lineal":
        result = LinearSearch.search(array_personas, search_attribute, query, starts_with)
    else:
        return "Método de búsqueda no válido"

    for persona in result:
        lista1.append(persona.serializable)
    
    return render_template('personas/listapersonas.html', lista=lista1)

@router.route('/facturas/buscar', methods=["GET"])
def buscar_facturas():
    query = request.args.get("query")
    search_attribute = request.args.get("searchAttribute")
    search_method = request.args.get("metodo_busqueda")
    starts_with = request.args.get("startsWith") == "true"

    fd = FacturaDaoControl()
    lista = fd._list()
    array_facturas = lista.toArray._array

    lista1 = []
    result = []

    if search_method == "binario":
        result = BinarySearch.search(array_facturas, search_attribute, query, starts_with)
    elif search_method == "lineal":
        result = LinearSearch.search(array_facturas, search_attribute, query, starts_with)
    else:
        return "Método de búsqueda no válido"

    for factura in result:
        lista1.append(factura.serializable)
    
    return render_template('facturas/listafacturas.html', lista=lista1)


templates/personas/eliminarpersonas.html
{% extends "templatepersonas.html" %}

{% block content %}
<div class="content-panel">
    <h2>¿Está seguro de que desea eliminar a esta persona?</h2>
    <p><strong>Apellidos y Nombres:</strong> {{ persona.apellidos }} {{ persona.nombres }}</p>
    <p><strong>DNI:</strong> {{ persona.dni }}</p>
    <p><strong>Teléfono:</strong> {{ persona.telefono }}</p>
    <p><strong>Dirección:</strong> {{ persona.direccion }}</p>
    <p><strong>Tipo RUC:</strong> {{ persona.tipoRuc }}</p>
    <form method="POST" action="{{ url_for('router.eliminar_persona', persona_id=persona.id) }}">
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{{ url_for('router.lista_personas') }}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/personas/guardarpersonas.html
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>KOPPEE - Coffee Shop HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free Website Template" name="keywords">
    <meta content="Free Website Template" name="description">

    <!-- Favicon -->
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon">

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400&family=Roboto:wght@400;500;700&display=swap"
        rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css') }}"
        rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{{ url_for('static', filename='css/style.min.css') }}" rel="stylesheet">
</head>

<body>
    <!-- Navbar Start -->
    <div class="container-fluid p-0 nav-bar">
        <nav class="navbar navbar-expand-lg bg-none navbar-dark py-3">
            <a href="templatepersonas.html" class="navbar-brand px-lg-4 m-0">
                <h1 class="m-0 display-4 text-uppercase text-white">sistema de Retencion de Facturas</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

    <!-- Page Header Start -->
    <div class="container-fluid page-header mb-5 position-relative overlay-bottom">
        <div class="d-flex flex-column align-items-center justify-content-center pt-0 pt-lg-5"
            style="min-height: 400px">
            <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">Registro de Personas</h1>
        </div>
    </div>
    <!-- Page Header End -->

    <div class="background-image">
        <div class="container content-panel p-4">
            <div class="card shadow">
                <div class="card-body">
                    <form id="form" class="custom-form booking-form" action="/personas/guardar" method="post"
                        role="form">
                        <div class="row">
                            <div class="col-lg-6 mb-3">
                                <label for="dni" class="form-label text-white">DNI:</label>
                                <input type="text" name="dni" class="form-control" id="dni" placeholder="Ingrese el DNI"
                                    required>
                            </div>
                            <div class="col-lg-6 mb-3">
                                <label for="apellidos" class="form-label text-white">Apellidos:</label>
                                <input type="text" name="apellidos" class="form-control" id="apellidos"
                                    placeholder="Ingrese los apellidos" required>
                            </div>
                            <div class="col-lg-6 mb-3">
                                <label for="nombres" class="form-label text-white">Nombres:</label>
                                <input type="text" name="nombres" class="form-control" id="nombres"
                                    placeholder="Ingrese los nombres" required>
                            </div>
                            <div class="col-lg-6 mb-3">
                                <label for="telefono" class="form-label text-white">Teléfono:</label>
                                <input type="text" name="telefono" class="form-control" id="telefono"
                                    placeholder="Ingrese el teléfono" required>
                            </div>
                            <div class="col-lg-6 mb-3">
                                <label for="direccion" class="form-label text-white">Dirección:</label>
                                <input type="text" name="direccion" class="form-control" id="direccion"
                                    placeholder="Ingrese la dirección" required>
                            </div>
                            <div class="col-lg-6 mb-3">
                                <label for="tipo_ruc" class="form-label text-white">Tipo de RUC:</label>
                                <select name="tipoRuc" class="form-select" id="tipo_ruc">
                                    <option value="8">RUC Educativo</option>
                                    <option value="10">RUC Profesional</option>
                                </select>
                            </div>

                            <div class="col-lg-12 mt-4">
                                <button id="boton" type="submit" class="form-control btn btn-primary">Guardar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="text-center mt-3">
                <a href="/personas" class="btn btn-danger">Volver</a>
            </div>
        </div>
    </div>


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/tempusdominus/js/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/tempusdominus/js/moment-timezone.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js') }}"></script>

    <!-- Contact Javascript File -->
    <script src="{{ url_for('static', filename='mail/jqBootstrapValidation.min.js') }}"></script>
    <script src="{{ url_for('static', filename='mail/contact.js') }}"></script>

    <!-- Template Javascript -->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>
{% endblock %}

templates/personas/listapersonas.html
{% extends "templatepersonas.html" %}

{% block content %}
<div class="content-panel">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <ul class="flashes">
        {% for category, message in messages %}
        <li class="flash-{{ category }}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}

    <!-- Title Section -->
    <div class="text-center mt-100 mb-4">
        <h1 class="display-20 text-uppercase text-black">LISTA DE PERSONAS</h1>
    </div>

    <!-- Formulario de Ordenación -->
    <div class="d-flex align-items-center mb-4">
        <form id="ordenarForm" action="/personas/ordenar" method="GET" class="ml-auto d-flex align-items-center">
            <!-- Combobox para ordenar -->
            <input type="hidden" name="sortMethod" id="sortMethod">
            <div class="ml-3">
                <label for="sortAttribute" class="mr-2">Atributo:</label>
                <select class="form-select" name="sortAttribute" id="sortAttribute" onclick="hidePlaceholder(this)">
                    <option value="_apellidos">Apellidos</option>
                    <option value="_direccion">Dirección</option>
                </select>
            </div>
            <div class="ml-3">
                <label for="sortOrder" class="mr-2">Orden:</label>
                <select class="form-select" name="sortOrder" id="sortOrder" onclick="hidePlaceholder(this)">
                    <option value="ascendente">Ascendente</option>
                    <option value="descendente">Descendente</option>
                </select>
            </div>
            <!-- Button to open the modal -->
            <button type="button" class="btn btn-info ml-2"
                style="background-color: #d67628; color: white; border: none; padding: 5px 10px; border-radius: 6px;"
                data-toggle="modal" data-target="#exampleModal">
                METODO DE ORDENACION
            </button>
            <button type="submit" class="btn btn-primary ml-2"
                style="background-color: #d67628; color: white; border: none; padding: 5px 10px; border-radius: 6px;">Aplicar</button>
        </form>
    </div>

    <div class="d-flex mb-4 align-items-center">
        <!-- Botón AGREGAR PERSONA -->
        <a href="personas/ver" class="btn btn-danger btn-sm mr-3" style="padding: 13px 15px; height: auto;">AGREGAR
            PERSONA</a>

        <!-- Formulario de Búsqueda -->
        <form id="formBusqueda" action="/personas/buscar" method="GET" class="flex-grow-1 d-flex align-items-center">
            <div class="input-group" style="max-width: 595px;">
                <input type="text" class="form-control rotating-placeholder" placeholder="Buscar" name="query"
                    id="query" required>
                <select class="form-select" name="searchAttribute" id="searchAttribute">
                    <option value="_apellidos">Apellidos</option>
                    <option value="_dni">Cedula</option>
                    <!-- Añadir más opciones según tus atributos -->
                </select>
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">Buscar</button>
                </div>
            </div>
            <div class="ml-3 d-flex align-items-center">
                <label for="metodo_busqueda" class="mr-2"></label>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-outline-secondary active">
                        <input type="radio" name="metodo_busqueda" id="binario" value="binario" autocomplete="off"
                            checked> Binaria
                    </label>
                    <label class="btn btn-outline-secondary">
                        <input type="radio" name="metodo_busqueda" id="lineal" value="lineal" autocomplete="off"> Lineal
                    </label>
                </div>
            </div>

            <!-- Nuevas opciones de Tipo de coincidencia -->
            <div class="ml-3">
                <div class="form-group">
                    <label class="text-black">Tipo de coincidencia</label>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="startsWith" id="anywhere" value="false"
                            checked>
                        <label class="form-check-label text-black" for="anywhere">En cualquier lugar</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="startsWith" id="start" value="true">
                        <label class="form-check-label text-black" for="start">Por inicial</label>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <style>
        .background-image {
            background-image: url("{{ url_for('static', filename='img/carousel-1.jpg') }}");
            background-size: cover;
            background-position: center;
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.min.css') }}">

    <!-- Tabla de Personas -->
    <div id="tablaContainer" class="table-container">
        <table id="tabla" class="table table-bordered table-hover">
            <thead class="thead-dark">
                <tr>
                    <th class="text-center">Nro</th>
                    <th class="text-center">Apellidos y Nombres</th>
                    <th class="text-center">DNI</th>
                    <th class="text-center">Teléfono</th>
                    <th class="text-center">Dirección</th>
                    <th class="text-center">Tipo RUC</th>
                    <th class="text-center">Acciones</th>
                    <th class="text-center">Factura</th>
                </tr>
            </thead>
            <tbody id="tablaCuerpo">
                {% for item in lista %}
                <tr id="persona_{{ item.id }}">
                    <td>{{ loop.index }}</td>
                    <td>{{ item.apellidos }} {{ item.nombres }}</td>
                    <td>{{ item.dni }}</td>
                    <td>{{ item.telefono }}</td>
                    <td>{{ item.direccion }}</td>
                    <td>
                        {% if item.tipoRuc == 'EDUCATIVO' %}
                        Educacional
                        {% elif item.tipoRuc == 'PROFESIONAL' %}
                        Profesional
                        {% else %}
                        Desconocido
                        {% endif %}
                    </td>
                    <td>
                        <div class="d-flex">
                            <a href="/facturas/ver?dni={{ item.dni }}&ruc={{ item.tipoRuc }}"
                                class="btn btn-primary btn-sm me-2">Agregar Factura</a>
                            <a href="/personas/editar/{{ item.id }}" class="btn btn-sm me-2"
                                style="background-color: #286ed6; color: white; border: none; padding: 5px 10px; border-radius: 2px;">MODIFICAR</a>
                            <form id="eliminar_form_{{ item.id }}" action="/personas/eliminar/{{ item.id }}"
                                method="POST">
                                <button type="submit" class="btn btn-sm"
                                    style="background-color: #e22e28; color: white; border: none; padding: 5px 10px; border-radius: 2*px;">Eliminar</button>
                            </form>
                        </div>
                    </td>
                    <td>
                        <a href="/facturas" class="btn btn-secondary btn-sm">Ver Facturas</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Selecciona un método</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="combobox">Opciones:</label>
                        <select class="form-control" id="combobox">
                            <option value="merge">Merge Sort</option>
                            <option value="quick">Quick Sort</option>
                            <option value="shell">Shell Sort</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="elegirMetodo">ELEGIR</button>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const placeholders = ["Buscar por apellidos", "Buscar por cédula"];
        let index = 0;
        const input = document.querySelector('.rotating-placeholder');

        setInterval(() => {
            index = (index + 1) % placeholders.length;
            input.placeholder = placeholders[index];
        }, 1000);

        // Script para actualizar el campo oculto con el método de ordenación seleccionado
        document.getElementById('elegirMetodo').addEventListener('click', function () {
            const metodo = document.getElementById('combobox').value;
            document.getElementById('sortMethod').value = metodo;
            $('#exampleModal').modal('hide');
        });

        // Script para ordenar la tabla basado en las opciones seleccionadas
        document.getElementById('ordenarForm').addEventListener('submit', function (event) {
            event.preventDefault();
            const attribute = document.getElementById('sortAttribute').value;
            const order = document.getElementById('sortOrder').value;
            const method = document.getElementById('sortMethod').value;
            sortTable(attribute, order, method);
        });

        function sortTable(attribute, order, method) {
            const tableBody = document.getElementById('tablaCuerpo');
            const rows = Array.from(tableBody.rows);
            const attributeIndex = getAttributeIndex(attribute);

            rows.sort((a, b) => {
                let valueA = a.cells[attributeIndex].textContent.trim();
                let valueB = b.cells[attributeIndex].textContent.trim();

                if (!isNaN(valueA) && !isNaN(valueB)) {
                    valueA = parseFloat(valueA);
                    valueB = parseFloat(valueB);
                }

                if (order === 'ascendente') {
                    return valueA > valueB ? 1 : -1;
                } else {
                    return valueA < valueB ? 1 : -1;
                }
            });

            while (tableBody.firstChild) {
                tableBody.removeChild(tableBody.firstChild);
            }

            tableBody.append(...rows);
        }

        function getAttributeIndex(attribute) {
            switch (attribute) {
                case '_apellidos':
                    return 1;
                case '_direccion':
                    return 4;
                // Agrega más casos si tienes más atributos
                default:
                    return 0;
            }
        }
    });
</script>

<script>
    $(document).ready(function () {
        $('form[id^="eliminar_form_"]').submit(function (event) {
            if (!confirm('¿Estás seguro de que deseas eliminar esta persona?')) {
                event.preventDefault();
            }
        });
    });
</script>
{% endblock %}